2014-01-22 17:33:43 Error: [MissingControllerException] Controller class ModelController could not be found.
Exception Attributes: array (
  'class' => 'ModelController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/model
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 17:42:43 Error: [MissingControllerException] Controller class ConsoleController could not be found.
Exception Attributes: array (
  'class' => 'ConsoleController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/console
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 17:42:48 Error: [MissingControllerException] Controller class ConsoleController could not be found.
Exception Attributes: array (
  'class' => 'ConsoleController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/Console
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 17:42:53 Error: [MissingControllerException] Controller class BakeController could not be found.
Exception Attributes: array (
  'class' => 'BakeController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/bake
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 17:43:02 Error: [MissingActionException] Action AppController::bake() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'bake',
)
Request URL: /vendaPassagens/app/bake
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-22 18:06:14 Error: [MissingActionException] Action AppController::webRoot() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'webRoot',
)
Request URL: /vendaPassagens/app/webRoot
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-22 18:07:46 Error: [MissingActionException] Action AppController::webroot() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'webroot',
)
Request URL: /vendaPassagens/app/webroot/
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-22 18:31:00 Error: [MissingControllerException] Controller class UsuarioController could not be found.
Exception Attributes: array (
  'class' => 'UsuarioController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 18:31:53 Error: [MissingControllerException] Controller class UsuarioController could not be found.
Exception Attributes: array (
  'class' => 'UsuarioController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 18:33:44 Error: Fatal Error (4): syntax error, unexpected '$array' (T_VARIABLE) in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuarioController.php, line 3]
2014-01-22 18:33:44 Error: [FatalErrorException] syntax error, unexpected '$array' (T_VARIABLE)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 18:34:04 Error: Fatal Error (4): syntax error, unexpected '$array' (T_VARIABLE) in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 3]
2014-01-22 18:34:04 Error: [FatalErrorException] syntax error, unexpected '$array' (T_VARIABLE)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 18:35:21 Error: [MissingControllerException] Controller class HelpersController could not be found.
Exception Attributes: array (
  'class' => 'HelpersController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/helpers
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 18:35:29 Error: [MissingActionException] Action AppController::helpers() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'helpers',
)
Request URL: /vendaPassagens/app/helpers
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-22 18:37:13 Error: [MissingActionException] Action AppController::index() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'index',
)
Request URL: /vendaPassagens/app/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-22 18:39:26 Error: Fatal Error (4): syntax error, unexpected '$array' (T_VARIABLE) in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 3]
2014-01-22 18:39:26 Error: [FatalErrorException] syntax error, unexpected '$array' (T_VARIABLE)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 18:39:38 Error: [MissingControllerException] Controller class UsuarioController could not be found.
Exception Attributes: array (
  'class' => 'UsuarioController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 18:39:47 Error: [MissingActionException] Action AppController::usuario() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'usuario',
)
Request URL: /vendaPassagens/app/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(AppController), Object(CakeRequest), Object(CakeResponse))
#2 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-22 18:39:58 Error: [MissingControllerException] Controller class UsuarioController could not be found.
Exception Attributes: array (
  'class' => 'UsuarioController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 18:40:19 Error: Fatal Error (4): syntax error, unexpected '$array' (T_VARIABLE) in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 3]
2014-01-22 18:40:19 Error: [FatalErrorException] syntax error, unexpected '$array' (T_VARIABLE)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 18:41:19 Error: Fatal Error (4): syntax error, unexpected '$array' (T_VARIABLE) in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 3]
2014-01-22 18:41:19 Error: [FatalErrorException] syntax error, unexpected '$array' (T_VARIABLE)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 20:54:46 Error: Fatal Error (4): syntax error, unexpected '$array' (T_VARIABLE) in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 3]
2014-01-22 20:54:46 Error: [FatalErrorException] syntax error, unexpected '$array' (T_VARIABLE)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 20:58:05 Error: Fatal Error (4): syntax error, unexpected '$array' (T_VARIABLE) in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 3]
2014-01-22 20:58:05 Error: [FatalErrorException] syntax error, unexpected '$array' (T_VARIABLE)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/opt/lampp/htdo...', 3, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 20:58:29 Error: Fatal Error (4): syntax error, unexpected '}', expecting ',' or ';' in [/opt/lampp/htdocs/vendaPassagens/app/Model/Usuario.php, line 4]
2014-01-22 20:58:29 Error: [FatalErrorException] syntax error, unexpected '}', expecting ',' or ';'
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/opt/lampp/htdo...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/opt/lampp/htdo...', 4, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/opt/lampp/htdo...', 4, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 20:58:53 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(8): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 20:59:57 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(8): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:00:08 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(8): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:01:01 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(8): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:01:10 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(8): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:01:26 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(8): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:01:44 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(8): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:01:58 Error: Fatal Error (1): Call to a member function find() on a non-object in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 8]
2014-01-22 21:01:58 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/lampp/htdo...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/lampp/htdo...', 8, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/lampp/htdo...', 8, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 21:02:46 Error: Fatal Error (4): syntax error, unexpected '$this' (T_VARIABLE) in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 9]
2014-01-22 21:02:46 Error: [FatalErrorException] syntax error, unexpected '$this' (T_VARIABLE)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/opt/lampp/htdo...', 9)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/opt/lampp/htdo...', 9, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/opt/lampp/htdo...', 9, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 21:02:55 Error: Fatal Error (4): syntax error, unexpected '$this' (T_VARIABLE) in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 9]
2014-01-22 21:02:55 Error: [FatalErrorException] syntax error, unexpected '$this' (T_VARIABLE)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/opt/lampp/htdo...', 9)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/opt/lampp/htdo...', 9, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/opt/lampp/htdo...', 9, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 21:03:00 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(9): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:03:30 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(9): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:05:16 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(9): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:07:54 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(9): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:08:20 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(8): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:10:14 Error: Fatal Error (1): Call to a member function find() on a non-object in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 8]
2014-01-22 21:10:14 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/lampp/htdo...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/lampp/htdo...', 8, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/lampp/htdo...', 8, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 21:11:32 Error: Fatal Error (1): Call to a member function find() on a non-object in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 8]
2014-01-22 21:11:32 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/lampp/htdo...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/lampp/htdo...', 8, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/lampp/htdo...', 8, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 21:11:35 Error: Fatal Error (1): Call to a member function find() on a non-object in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 8]
2014-01-22 21:11:35 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/lampp/htdo...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/lampp/htdo...', 8, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/lampp/htdo...', 8, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 21:11:52 Error: Fatal Error (1): Call to a member function find() on a non-object in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 8]
2014-01-22 21:11:52 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/lampp/htdo...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/lampp/htdo...', 8, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/lampp/htdo...', 8, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 21:12:10 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios/index
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(8): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:13:35 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(8): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:14:55 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(8): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:15:47 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(8): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:15:49 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php(8): Model->find('all')
#4 [internal function]: UsuariosController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:16:42 Error: [MissingControllerException] Controller class UsuariosController could not be found.
Exception Attributes: array (
  'class' => 'UsuariosController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 21:16:49 Error: [MissingControllerException] Controller class UsuarioController could not be found.
Exception Attributes: array (
  'class' => 'UsuarioController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 21:17:44 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuarioController.php(8): Model->find('all')
#4 [internal function]: UsuarioController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuarioController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuarioController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:18:03 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuarioController.php(8): Model->find('all')
#4 [internal function]: UsuarioController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuarioController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuarioController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:18:44 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuarioController.php(8): Model->find('all')
#4 [internal function]: UsuarioController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuarioController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuarioController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:18:47 Error: [MissingControllerException] Controller class UsuariosController could not be found.
Exception Attributes: array (
  'class' => 'UsuariosController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 21:18:52 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuarioController.php(8): Model->find('all')
#4 [internal function]: UsuarioController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuarioController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuarioController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:19:03 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuarioController.php(8): Model->find('all')
#4 [internal function]: UsuarioController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuarioController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuarioController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:19:25 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuarioController.php(8): Model->find('all')
#4 [internal function]: UsuarioController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuarioController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuarioController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:20:20 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuarioController.php(8): Model->find('all')
#4 [internal function]: UsuarioController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuarioController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuarioController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:20:47 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuarioController.php(8): Model->find('all')
#4 [internal function]: UsuarioController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuarioController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuarioController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:23:00 Error: [MissingControllerException] Controller class UsuariosController could not be found.
Exception Attributes: array (
  'class' => 'UsuariosController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 21:23:04 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(3493): Model->setSource('usuarios')
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2897): Model->getDataSource()
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Model/Model.php(2869): Model->_readDataSource('all', Array)
#3 /opt/lampp/htdocs/vendaPassagens/app/Controller/UsuarioController.php(8): Model->find('all')
#4 [internal function]: UsuarioController->index()
#5 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(UsuarioController), Array)
#6 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuarioController), Object(CakeRequest), Object(CakeResponse))
#8 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-22 21:24:15 Error: [MissingControllerException] Controller class UsuarioController could not be found.
Exception Attributes: array (
  'class' => 'UsuarioController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/usuario
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 21:24:20 Error: [MissingControllerException] Controller class UsuariosController could not be found.
Exception Attributes: array (
  'class' => 'UsuariosController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 21:26:29 Error: [MissingViewException] View file "/opt/lampp/htdocs/vendaPassagens/app/View/Usuario/index.ctp" is missing.
Exception Attributes: array (
  'file' => '/opt/lampp/htdocs/vendaPassagens/app/View/Usuario/index.ctp',
)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/View/View.php(457): View->_getViewFileName(NULL)
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(952): View->render(NULL, NULL)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#4 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-22 21:31:12 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/posts/view/1
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 21:40:30 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/posts/view/1
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 21:42:34 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/posts/view/1
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 21:42:38 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/posts/view/1
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 21:43:57 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/posts/view/1
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 21:44:08 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/posts/view/1
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 21:45:18 Error: [MissingViewException] View file "/opt/lampp/htdocs/vendaPassagens/app/View/Usuarios/index.ctp" is missing.
Exception Attributes: array (
  'file' => '/opt/lampp/htdocs/vendaPassagens/app/View/Usuarios/index.ctp',
)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/View/View.php(457): View->_getViewFileName(NULL)
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(952): View->render(NULL, NULL)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#4 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-22 21:45:52 Error: [MissingViewException] View file "/opt/lampp/htdocs/vendaPassagens/app/View/Usuarios/index.ctp" is missing.
Exception Attributes: array (
  'file' => '/opt/lampp/htdocs/vendaPassagens/app/View/Usuarios/index.ctp',
)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/View/View.php(457): View->_getViewFileName(NULL)
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(952): View->render(NULL, NULL)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#4 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-22 21:46:18 Error: [MissingViewException] View file "/opt/lampp/htdocs/vendaPassagens/app/View/Usuarios/index.ctp" is missing.
Exception Attributes: array (
  'file' => '/opt/lampp/htdocs/vendaPassagens/app/View/Usuarios/index.ctp',
)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/View/View.php(457): View->_getViewFileName(NULL)
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(952): View->render(NULL, NULL)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#4 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-22 21:46:46 Error: [MissingViewException] View file "/opt/lampp/htdocs/vendaPassagens/app/View/Usuarios/index.ctp" is missing.
Exception Attributes: array (
  'file' => '/opt/lampp/htdocs/vendaPassagens/app/View/Usuarios/index.ctp',
)
Request URL: /vendaPassagens/usuarios
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/View/View.php(457): View->_getViewFileName(NULL)
#1 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Controller/Controller.php(952): View->render(NULL, NULL)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#4 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-22 22:05:17 Error: Fatal Error (4): syntax error, unexpected '}' in [/opt/lampp/htdocs/vendaPassagens/app/Controller/UsuariosController.php, line 21]
2014-01-22 22:05:17 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /vendaPassagens/usuarios/view/add
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/opt/lampp/htdo...', 21)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/opt/lampp/htdo...', 21, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/opt/lampp/htdo...', 21, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 22:06:13 Error: [MissingControllerException] Controller class UsuarioController could not be found.
Exception Attributes: array (
  'class' => 'UsuarioController',
  'plugin' => NULL,
)
Request URL: /vendaPassagens/usuario/view/add
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-22 22:07:26 Error: Fatal Error (1): Call to a member function create() on a non-object in [/opt/lampp/htdocs/vendaPassagens/app/View/Usuarios/add.ctp, line 3]
2014-01-22 22:07:26 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /vendaPassagens/usuarios/add
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/lampp/htdo...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/lampp/htdo...', 3, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/lampp/htdo...', 3, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 22:07:49 Error: Fatal Error (1): Call to a member function create() on a non-object in [/opt/lampp/htdocs/vendaPassagens/app/View/Usuarios/add.ctp, line 3]
2014-01-22 22:07:49 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /vendaPassagens/usuarios/add
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/lampp/htdo...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/lampp/htdo...', 3, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/lampp/htdo...', 3, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 22:08:53 Error: Fatal Error (1): Call to a member function create() on a non-object in [/opt/lampp/htdocs/vendaPassagens/app/View/Usuarios/add.ctp, line 3]
2014-01-22 22:08:53 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /vendaPassagens/usuarios/add
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/lampp/htdo...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/lampp/htdo...', 3, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/lampp/htdo...', 3, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-22 22:17:38 Error: Fatal Error (1): Call to a member function create() on a non-object in [/opt/lampp/htdocs/vendaPassagens/app/View/Usuarios/add.ctp, line 3]
2014-01-22 22:17:38 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /vendaPassagens/usuarios/add
Stack Trace:
#0 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/opt/lampp/htdo...', 3)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/opt/lampp/htdo...', 3, Array)
#2 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/opt/lampp/htdo...', 3, Array)
#3 /opt/lampp/htdocs/vendaPassagens/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 13:48:30 Error: [MissingControllerException] Controller class UsariosController could not be found.
Exception Attributes: array (
  'class' => 'UsariosController',
  'plugin' => NULL,
)
Request URL: /VendaDePassagens/usarios
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-23 13:58:26 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-23 13:59:12 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-23 14:13:52 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-23 14:17:03 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-23 14:25:22 Error: Fatal Error (64): Cannot redeclare UsersController::$components in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php, line 7]
2014-01-23 14:25:22 Error: [FatalErrorException] Cannot redeclare UsersController::$components
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 7, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 7, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 14:25:45 Error: Fatal Error (64): Cannot redeclare UsersController::$components in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php, line 7]
2014-01-23 14:25:45 Error: [FatalErrorException] Cannot redeclare UsersController::$components
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 7, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 7, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 14:31:32 Error: Fatal Error (4): syntax error, unexpected '09' (T_LNUMBER) in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php, line 11]
2014-01-23 14:31:32 Error: [FatalErrorException] syntax error, unexpected '09' (T_LNUMBER)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 14:32:14 Error: Fatal Error (4): syntax error, unexpected '09' (T_LNUMBER) in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php, line 11]
2014-01-23 14:32:14 Error: [FatalErrorException] syntax error, unexpected '09' (T_LNUMBER)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 11, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 11, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 14:50:58 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php, line 56]
2014-01-23 14:50:58 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 56)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 56, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 56, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 14:59:42 Error: [MissingActionException] Action UsuariosController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsuariosController',
  'action' => 'login',
)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-23 15:00:26 Error: [MissingActionException] Action UsuariosController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsuariosController',
  'action' => 'login',
)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-23 15:01:01 Error: [MissingActionException] Action UsuariosController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsuariosController',
  'action' => 'login',
)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-23 15:01:27 Error: [MissingActionException] Action UsuariosController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsuariosController',
  'action' => 'login',
)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-23 15:02:39 Error: [MissingActionException] Action UsuariosController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsuariosController',
  'action' => 'login',
)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-23 15:03:03 Error: [MissingActionException] Action UsuariosController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsuariosController',
  'action' => 'login',
)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-23 15:03:16 Error: [MissingActionException] Action UsuariosController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsuariosController',
  'action' => 'login',
)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-23 15:03:34 Error: [MissingActionException] Action UsuariosController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsuariosController',
  'action' => 'login',
)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-23 15:03:41 Error: [MissingActionException] Action UsuariosController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsuariosController',
  'action' => 'login',
)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-23 15:04:08 Error: [MissingActionException] Action UsuariosController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsuariosController',
  'action' => 'login',
)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsuariosController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-01-23 15:05:10 Error: Fatal Error (4): syntax error, unexpected 'unction' (T_STRING), expecting function (T_FUNCTION) in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsuariosController.php, line 8]
2014-01-23 15:05:10 Error: [FatalErrorException] syntax error, unexpected 'unction' (T_STRING), expecting function (T_FUNCTION)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 8, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 15:09:02 Error: Fatal Error (64): Cannot redeclare UsersController::beforeFilter() in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php, line 64]
2014-01-23 15:09:02 Error: [FatalErrorException] Cannot redeclare UsersController::beforeFilter()
Request URL: /VendaDePassagens/users/add
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 64)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 64, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 64, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 15:18:29 Error: Fatal Error (1): Call to a member function save() on a non-object in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php, line 52]
2014-01-23 15:18:29 Error: [FatalErrorException] Call to a member function save() on a non-object
Request URL: /VendaDePassagens/users/add
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 52, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 52, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 15:18:39 Error: Fatal Error (1): Call to a member function save() on a non-object in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php, line 52]
2014-01-23 15:18:39 Error: [FatalErrorException] Call to a member function save() on a non-object
Request URL: /VendaDePassagens/users/add
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 52)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 52, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 52, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 15:30:53 Error: Fatal Error (4): syntax error, unexpected 'if' (T_IF) in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php, line 24]
2014-01-23 15:30:53 Error: [FatalErrorException] syntax error, unexpected 'if' (T_IF)
Request URL: /VendaDePassagens/users/add
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 24)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 24, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 24, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 15:39:49 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /VendaDePassagens/posts/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-23 15:41:10 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /VendaDePassagens/posts/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-23 15:42:09 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /VendaDePassagens/posts/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-23 15:47:12 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\VendaDePassagens\app\Controller\AppController.php, line 49]
2014-01-23 15:47:12 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 49)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 49, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 49, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 15:49:14 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\VendaDePassagens\app\Controller\AppController.php, line 49]
2014-01-23 15:49:14 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 49)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 49, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 49, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 15:52:25 Error: Fatal Error (4): syntax error, unexpected 'Debugger' (T_STRING), expecting function (T_FUNCTION) in [C:\xampp\htdocs\VendaDePassagens\app\Controller\AppController.php, line 50]
2014-01-23 15:52:25 Error: [FatalErrorException] syntax error, unexpected 'Debugger' (T_STRING), expecting function (T_FUNCTION)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 50)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 50, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 50, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 15:58:47 Error: Fatal Error (4): syntax error, unexpected 'if' (T_IF) in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php, line 72]
2014-01-23 15:58:47 Error: [FatalErrorException] syntax error, unexpected 'if' (T_IF)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 72)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 72, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 72, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 16:04:52 Error: Fatal Error (4): syntax error, unexpected 'if' (T_IF) in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php, line 72]
2014-01-23 16:04:52 Error: [FatalErrorException] syntax error, unexpected 'if' (T_IF)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 72)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 72, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 72, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 16:19:11 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsuariosController.php, line 66]
2014-01-23 16:19:11 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 66)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 66, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 66, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 16:27:56 Error: Fatal Error (4): syntax error, unexpected '-', expecting function (T_FUNCTION) in [C:\xampp\htdocs\VendaDePassagens\app\Controller\AppController.php, line 54]
2014-01-23 16:27:56 Error: [FatalErrorException] syntax error, unexpected '-', expecting function (T_FUNCTION)
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 54)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 54, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 54, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 16:28:16 Error: Fatal Error (1): Call to a member function flash() on a non-object in [C:\xampp\htdocs\VendaDePassagens\app\View\Usuarios\login.ctp, line 1]
2014-01-23 16:28:16 Error: [FatalErrorException] Call to a member function flash() on a non-object
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 1)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 1, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 1, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 16:29:12 Error: Fatal Error (1): Call to a member function flash() on a non-object in [C:\xampp\htdocs\VendaDePassagens\app\View\Usuarios\login.ctp, line 1]
2014-01-23 16:29:12 Error: [FatalErrorException] Call to a member function flash() on a non-object
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 1)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 1, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 1, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 18:30:08 Error: [MissingViewException] View file "C:\xampp\htdocs\VendaDePassagens\app\View\Users\add.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\VendaDePassagens\\app\\View\\Users\\add.ctp',
)
Request URL: /VendaDePassagens/users/add
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\View.php(457): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-23 18:30:33 Error: [MissingViewException] View file "C:\xampp\htdocs\VendaDePassagens\app\View\Users\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\VendaDePassagens\\app\\View\\Users\\login.ctp',
)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\View.php(457): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-23 18:32:11 Error: [MissingViewException] View file "C:\xampp\htdocs\VendaDePassagens\app\View\Users\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\VendaDePassagens\\app\\View\\Users\\login.ctp',
)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\View.php(457): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-23 18:32:20 Error: Fatal Error (64): Cannot redeclare Usuario::$name in [C:\xampp\htdocs\VendaDePassagens\app\Model\Usuario.php, line 5]
2014-01-23 18:32:20 Error: [FatalErrorException] Cannot redeclare Usuario::$name
Request URL: /VendaDePassagens/usuarios/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 5)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 5, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 5, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 18:53:46 Error: [MissingViewException] View file "C:\xampp\htdocs\VendaDePassagens\app\View\Users\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\VendaDePassagens\\app\\View\\Users\\login.ctp',
)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\View.php(457): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-01-23 18:54:23 Error: Fatal Error (64): Cannot redeclare class Usuario in [C:\xampp\htdocs\VendaDePassagens\app\Model\User.php, line 34]
2014-01-23 18:54:23 Error: [FatalErrorException] Cannot redeclare class Usuario
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 34)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 34, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 34, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 18:55:38 Error: Fatal Error (64): Cannot redeclare class Usuario in [C:\xampp\htdocs\VendaDePassagens\app\Model\User.php, line 34]
2014-01-23 18:55:38 Error: [FatalErrorException] Cannot redeclare class Usuario
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 34)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 34, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 34, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 18:56:41 Error: Fatal Error (64): Cannot redeclare class Usuario in [C:\xampp\htdocs\VendaDePassagens\app\Model\User.php, line 34]
2014-01-23 18:56:41 Error: [FatalErrorException] Cannot redeclare class Usuario
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 34)
#1 [internal function]: ErrorHandler::handleError(64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 34, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 64, 'Cannot redeclar...', 'C:\xampp\htdocs...', 34, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 18:57:17 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.username' in 'where clause'
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(664): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(1076): DboSource->fetchAll('SELECT `User`.`...', false)
#4 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(2897): DboSource->read(Object(User), Array)
#5 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(2869): Model->_readDataSource('first', Array)
#6 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\Auth\BaseAuthenticate.php(114): Model->find('first', Array)
#7 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\Auth\FormAuthenticate.php(81): BaseAuthenticate->_findUser('euler', '123456')
#8 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\AuthComponent.php(750): FormAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\AuthComponent.php(597): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#10 C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php(13): AuthComponent->login()
#11 [internal function]: UsersController->login()
#12 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#13 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#14 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#15 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-01-23 19:00:48 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.username' in 'where clause'
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(664): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(1076): DboSource->fetchAll('SELECT `User`.`...', false)
#4 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(2897): DboSource->read(Object(User), Array)
#5 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(2869): Model->_readDataSource('first', Array)
#6 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\Auth\BaseAuthenticate.php(114): Model->find('first', Array)
#7 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\Auth\FormAuthenticate.php(81): BaseAuthenticate->_findUser('euler@ufba.br', '123456')
#8 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\AuthComponent.php(750): FormAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\AuthComponent.php(597): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#10 C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php(14): AuthComponent->login()
#11 [internal function]: UsersController->login()
#12 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#13 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#14 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#15 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-01-23 19:02:10 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.username' in 'where clause'
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(664): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(1076): DboSource->fetchAll('SELECT `User`.`...', false)
#4 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(2897): DboSource->read(Object(User), Array)
#5 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(2869): Model->_readDataSource('first', Array)
#6 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\Auth\BaseAuthenticate.php(114): Model->find('first', Array)
#7 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\Auth\FormAuthenticate.php(81): BaseAuthenticate->_findUser('euler@ufba.br', '123456')
#8 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\AuthComponent.php(750): FormAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\AuthComponent.php(597): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#10 C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php(17): AuthComponent->login()
#11 [internal function]: UsersController->login()
#12 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#13 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#14 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#15 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-01-23 19:03:43 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.username' in 'where clause'
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(664): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(1076): DboSource->fetchAll('SELECT `User`.`...', false)
#4 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(2897): DboSource->read(Object(User), Array)
#5 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(2869): Model->_readDataSource('first', Array)
#6 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\Auth\BaseAuthenticate.php(114): Model->find('first', Array)
#7 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\Auth\FormAuthenticate.php(81): BaseAuthenticate->_findUser('euler@ufba.br', '123456')
#8 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\AuthComponent.php(750): FormAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\AuthComponent.php(597): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#10 C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php(17): AuthComponent->login()
#11 [internal function]: UsersController->login()
#12 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#13 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#14 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#15 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-01-23 19:31:14 Error: [MissingTableException] Table usuarios for model User was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'User',
  'ds' => 'default',
)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(3493): Model->setSource('usuarios')
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(1353): Model->getDataSource()
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\Helper\FormHelper.php(199): Model->schema()
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\Helper\FormHelper.php(451): FormHelper->_introspectModel('User', 'fields')
#4 C:\xampp\htdocs\VendaDePassagens\app\View\Users\login.ctp(3): FormHelper->create('User')
#5 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\View.php(929): include('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\View.php(891): View->_evaluate('C:\xampp\htdocs...', Array)
#7 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\View.php(460): View->_render('C:\xampp\htdocs...')
#8 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#9 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#10 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-01-23 19:43:43 Error: Fatal Error (1): Call to a member function save() on a non-object in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php, line 49]
2014-01-23 19:43:43 Error: [FatalErrorException] Call to a member function save() on a non-object
Request URL: /VendaDePassagens/users/add
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 49)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 49, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 49, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 19:44:13 Error: Fatal Error (1): Call to a member function save() on a non-object in [C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php, line 49]
2014-01-23 19:44:13 Error: [FatalErrorException] Call to a member function save() on a non-object
Request URL: /VendaDePassagens/users/add
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 49)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 49, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 49, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 19:47:48 Error: [MissingTableException] Table rotas for model Rota was not found in datasource default.
Exception Attributes: array (
  'table' => 'rotas',
  'class' => 'Rota',
  'ds' => 'default',
)
Request URL: /VendaDePassagens/Rotas/
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(3493): Model->setSource('rotas')
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(2897): Model->getDataSource()
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(2869): Model->_readDataSource('all', Array)
#3 C:\xampp\htdocs\VendaDePassagens\app\Controller\RotasController.php(11): Model->find('all')
#4 [internal function]: RotasController->index()
#5 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(RotasController), Array)
#6 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(RotasController), Object(CakeRequest), Object(CakeResponse))
#8 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-01-23 19:50:23 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /VendaDePassagens/users/add
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(3493): Model->setSource('usuarios')
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(1353): Model->getDataSource()
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\Helper\FormHelper.php(199): Model->schema()
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\Helper\FormHelper.php(451): FormHelper->_introspectModel('Usuario', 'fields')
#4 C:\xampp\htdocs\VendaDePassagens\app\View\Users\add.ctp(3): FormHelper->create('Usuario')
#5 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\View.php(929): include('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\View.php(891): View->_evaluate('C:\xampp\htdocs...', Array)
#7 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\View.php(460): View->_render('C:\xampp\htdocs...')
#8 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#9 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#10 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-01-23 19:51:56 Error: [MissingTableException] Table usuarios for model Usuario was not found in datasource default.
Exception Attributes: array (
  'table' => 'usuarios',
  'class' => 'Usuario',
  'ds' => 'default',
)
Request URL: /VendaDePassagens/users/add
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(3493): Model->setSource('usuarios')
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(1353): Model->getDataSource()
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\Helper\FormHelper.php(199): Model->schema()
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\Helper\FormHelper.php(451): FormHelper->_introspectModel('Usuario', 'fields')
#4 C:\xampp\htdocs\VendaDePassagens\app\View\Users\add.ctp(3): FormHelper->create('Usuario')
#5 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\View.php(929): include('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\View.php(891): View->_evaluate('C:\xampp\htdocs...', Array)
#7 C:\xampp\htdocs\VendaDePassagens\lib\Cake\View\View.php(460): View->_render('C:\xampp\htdocs...')
#8 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#9 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#10 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-01-23 20:33:33 Error: Fatal Error (1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 62914560 bytes) in [C:\xampp\htdocs\VendaDePassagens\lib\Cake\basics.php, line 117]
2014-01-23 20:33:33 Error: [FatalErrorException] Allowed memory size of 134217728 bytes exhausted (tried to allocate 62914560 bytes)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Allowed memory ...', 'C:\xampp\htdocs...', 117)
#1 [internal function]: ErrorHandler::handleError(1, 'Allowed memory ...', 'C:\xampp\htdocs...', 117, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Allowed memory ...', 'C:\xampp\htdocs...', 117, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 20:34:08 Error: Fatal Error (1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 62914560 bytes) in [C:\xampp\htdocs\VendaDePassagens\lib\Cake\basics.php, line 117]
2014-01-23 20:34:08 Error: [FatalErrorException] Allowed memory size of 134217728 bytes exhausted (tried to allocate 62914560 bytes)
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Allowed memory ...', 'C:\xampp\htdocs...', 117)
#1 [internal function]: ErrorHandler::handleError(1, 'Allowed memory ...', 'C:\xampp\htdocs...', 117, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Allowed memory ...', 'C:\xampp\htdocs...', 117, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 20:36:33 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.username' in 'where clause'
Request URL: /VendaDePassagens/users/login
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `User`.`...', Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(664): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Datasource\DboSource.php(1076): DboSource->fetchAll('SELECT `User`.`...', false)
#4 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(2897): DboSource->read(Object(User), Array)
#5 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Model\Model.php(2869): Model->_readDataSource('first', Array)
#6 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\Auth\BaseAuthenticate.php(114): Model->find('first', Array)
#7 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\Auth\FormAuthenticate.php(81): BaseAuthenticate->_findUser('eueru', '12313131')
#8 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\AuthComponent.php(750): FormAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#9 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Component\AuthComponent.php(597): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#10 C:\xampp\htdocs\VendaDePassagens\app\Controller\UsersController.php(14): AuthComponent->login()
#11 [internal function]: UsersController->login()
#12 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#13 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#14 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#15 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2014-01-23 20:43:33 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\VendaDePassagens\app\View\Users\add.ctp, line 6]
2014-01-23 20:43:33 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /VendaDePassagens/users/add
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 6)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 6, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 6, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-01-23 20:48:26 Error: [MissingControllerException] Controller class Controller could not be found.
Exception Attributes: array (
  'class' => 'Controller',
  'plugin' => NULL,
)
Request URL: /VendaDePassagens/
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-23 20:48:34 Error: [MissingControllerException] Controller class Controller could not be found.
Exception Attributes: array (
  'class' => 'Controller',
  'plugin' => NULL,
)
Request URL: /VendaDePassagens/
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-23 20:49:24 Error: [MissingControllerException] Controller class Controller could not be found.
Exception Attributes: array (
  'class' => 'Controller',
  'plugin' => NULL,
)
Request URL: /VendaDePassagens/
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-01-23 20:57:07 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\VendaDePassagens\app\View\Users\index.ctp, line 47]
2014-01-23 20:57:07 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /VendaDePassagens/users/index/loggedin
Stack Trace:
#0 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 47, Array)
#2 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 47, Array)
#3 C:\xampp\htdocs\VendaDePassagens\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
